#
# @auther:nosuke
# 
version: '3'
services:
# free HTTPS compatible
# https://letsencrypt.org/
  https-portal:
    image: steveltn/https-portal:1
    container_name: https
    env_file: .env
    ports:
      - '${HTTPS_HOST_PORT_80}:80'
      - '${HTTPS_HOST_PORT_443}:443'
    environment:
      DOMAINS: 'nontitle.xyz -> http://dockerhost:${NGINX_HOST_PORT_8000}/' 
# Test-signed certificate
      STAGE: 'staging'
# Self-signed certificate
#      STAGE: 'local'
# Production signed certificate
#      STAGE: 'production'
    depends_on:
      - nginx

# Nginx
  nginx:
    image: nginx:stable
    container_name: nginx
    restart: always
    env_file: .env
    ports:
      - '${NGINX_HOST_PORT_8000}:8000'
    depends_on:
      - wordpress
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./wordpress:/var/www/html

# wordpres
# Note:Please select a version without Apache
  wordpress:
    image: wordpress:php7.3-fpm
    container_name: wordpress
    restart: always
    env_file: .env
    environment:
      - WORDPRESS_DB_HOST=${WORDPRESS_DB_HOST}
      - WORDPRESS_DB_USER=${WORDPRESS_DB_USER}
      - WORDPRESS_DB_PASSWORD=${WORDPRESS_DB_PASSWORD}
      - WORDPRESS_DB_NAME=${WORDPRESS_DB_NAME}
    volumes:
      - ./wordpress:/var/www/html
    depends_on:
      - mysql

# MariaDB
  mysql:
    image: mariadb:latest
    container_name: mysql
    restart: always
    env_file: .env
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    ports:
      - '${MYSQL_HOST_PORT_3306}:3306'
    volumes:
        - ./mysql:/var/lib/mysql